---
title: "AbortionByState"
format: html
editor: visual
---

# Imports

## Packages

```{r}
#install.packages("tidyverse")
#install.packages("rvest")
#install.packages("janitor")
#install.packages("stringr")
#install.packages("httr2")
library(stringr)
library(tidyverse)
library(rvest)
library(janitor)
library(httr2)
```

## Laws by State

```{r}
law_data_raw <- read_csv("raw_data.csv")
```

## Unemployment by State

```{r}
key="05ec8ecf241642429022e023379cbb21"
url="https://api.bls.gov/publicAPI/v2/timeseries/data/"
ma_id="LAUST250000000000003"
me_id="LAUST230000000000003"
nh_id="LAUST330000000000003"
vt_id="LAUST500000000000003"
ri_id="LAUST440000000000003"
ct_id="LAUST090000000000003"

ma_unemployment <-request(url) |>
  req_body_json(list(
    seriesid=list(ma_id),
    startyear="2011",
    endyear="2022",
    registrationkey=key
    )) |>
  req_perform() |>
  resp_body_json()

me_unemployment <-request(url) |>
  req_body_json(list(
    seriesid=list(me_id),
    startyear="2011",
    endyear="2022",
    registrationkey=key
    )) |>
  req_perform() |>
  resp_body_json()

nh_unemployment <-request(url) |>
  req_body_json(list(
    seriesid=list(nh_id),
    startyear="2011",
    endyear="2022",
    registrationkey=key
    )) |>
  req_perform() |>
  resp_body_json()

ct_unemployment <-request(url) |>
  req_body_json(list(
    seriesid=list(ct_id),
    startyear="2011",
    endyear="2022",
    registrationkey=key
    )) |>
  req_perform() |>
  resp_body_json()

ri_unemployment <-request(url) |>
  req_body_json(list(
    seriesid=list(ri_id),
    startyear="2011",
    endyear="2022",
    registrationkey=key
    )) |>
  req_perform() |>
  resp_body_json()

vt_unemployment <-request(url) |>
  req_body_json(list(
    seriesid=list(vt_id),
    startyear="2011",
    endyear="2022",
    registrationkey=key
    )) |>
  req_perform() |>
  resp_body_json()
```

## Abortion Data By State

```{r}
new_england=c("Maine","Vermont","New Hampshire","Massachusetts","Connecticut","Rhode Island")

read_file <- function(year){
  file_name=str_c("Abortions-Distributed-by-Area-",year,".csv")
  read_csv(file_name) |>
    rename(data=contains("These data are consistent with"))|>
    mutate(year=year)|>
    select(2,60,year)|>
    rename(state=contains("2"),total=contains("60"))|>
    filter(state%in%new_england|str_detect(state,pattern="New Hamp"))
}

all_abortion_data <- map_dfr(2011:2022,read_file)
```
